version: '3.1'

services:
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:4.6
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./src/:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  # Database
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      # - db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db:
